version: '3.2'
services:
  mysql57:
    container_name: "mysql57"
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: yomuyodb
        MYSQL_ROOT_PASSWORD: naishodayo
    ports:
      - "3306"
    restart: always
    volumes:
      - "../../db:/var/lib/mysql"
  nginx:
    container_name: "nginx"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - "./public:/app/public/"
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    restart: always
  php-fpm:
    container_name: "php-fpm"
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - "./:/app/"
    restart: always
    links:
     - mysql57
  pma:
    container_name: "pma"
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql57
    ports:
    - "8080:80"
    restart: always
    links:
     - mysql57


  nginx_for_schemaspy:
    image: nginx:1.13.9-alpine
    container_name: nginx_for_schemaspy
    volumes:
      - ./schemaspy:/var/www/html:ro
      - ./docker/nginx_for_schemaspy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"
  schemaspy:
    build: ./docker/schemaspy
    image: treetips/schemaspy-mysql
    container_name: schemaspy
    volumes:
      - ./schemaspy:/app/html:rw
      - ./docker/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    working_dir: "/app"
    command: "java -jar schemaspy.jar"

